AY2324S1-CS2103T-T15-2/tp

- docs/UserGuide.md
Standardise some formatting and remove some instances of AB3 in the following sections
Add feature
Saving the data
Editing the data file
FAQ
Command summary
> Edit add feature, command summary in user guide

- docs/DevOps.md
- docs/DeveloperGuide.md
Many details still need to be discussed over. This serves as a foundation to build upon.
> First draft of Developer Guide

- docs/DeveloperGuide.md
Add Use Case for list today command.  Edited small typosd
> Add Use Case for List Today command

- src/main/java/seedu/address/logic/commands/DeletePrescriptionCommand.java
- src/test/java/seedu/address/logic/commands/DeletePrescriptionCommandTest.java
- src/test/java/seedu/address/logic/parser/DeletePrescriptionCommandParserTest.java
Lets improve our test coverage to cover all prescription related code.
> Branch testdelete

- src/main/java/seedu/address/logic/commands/TakePrescriptionCommand.java
- src/main/java/seedu/address/model/prescription/ConsumptionCount.java
- src/main/java/seedu/address/model/prescription/Date.java
- src/main/java/seedu/address/model/prescription/Dosage.java
- src/main/java/seedu/address/model/prescription/Frequency.java
- src/main/java/seedu/address/model/prescription/Name.java
- src/main/java/seedu/address/model/prescription/Note.java
- src/main/java/seedu/address/model/prescription/Stock.java
- src/test/java/seedu/address/logic/commands/ListTodayPrescriptionCommandTest.java
- src/test/java/seedu/address/logic/commands/TakePrescriptionCommandTest.java
- src/test/java/seedu/address/logic/parser/TakePrescriptionCommandParserTest.java
- src/test/java/seedu/address/model/prescription/ConsumptionCountTest.java
- src/test/java/seedu/address/testutil/PrescriptionUtil.java
Lets improve our test coverage to cover all prescription related code.
> Add tests for TakePrescriptionCommand and TakePrescriptionCommandParser

- src/main/java/seedu/address/logic/commands/ListCommand.java
- src/test/java/seedu/address/logic/LogicManagerTest.java
As discussed literally just now.
> Standardise List cmd to ListToday

- src/main/java/seedu/address/logic/commands/HelpCommand.java
- src/main/java/seedu/address/logic/parser/HelpCommandParser.java
- src/main/java/seedu/address/logic/parser/ListCommandParser.java
- src/main/java/seedu/address/logic/parser/PrescriptionListParser.java
- src/main/java/seedu/address/ui/HelpWindow.java
- src/test/java/seedu/address/logic/parser/HelpCommandParserTest.java
Lets add help command to help our users who navigate to our User Guide if they need assistance in using BayMeds.
> Add help command

- src/main/resources/view/MainWindowPrescription.fxml
> Change Name of Adress Book

- src/main/java/seedu/address/logic/commands/DeleteCommand.java
- src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
- src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
As mentioned in the team meeting, lets:
* change the command format of delete
* maintain safeguards against malicious input
> Edit delete command

- src/main/java/seedu/address/logic/Messages.java
- src/main/java/seedu/address/logic/commands/AddCommand.java
- src/main/java/seedu/address/logic/commands/EditCommand.java
- src/main/java/seedu/address/logic/commands/ExitCommand.java
- src/main/java/seedu/address/logic/commands/TakeCommand.java
- src/main/java/seedu/address/logic/parser/AddCommandParser.java
- src/main/java/seedu/address/model/prescription/IsTodayPredicate.java
- src/main/java/seedu/address/model/prescription/IsValidDatesPredicate.java
- src/main/java/seedu/address/model/prescription/Prescription.java
- src/main/java/seedu/address/storage/JsonAdaptedPrescription.java
- src/main/java/seedu/address/ui/PrescriptionCard.java
- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
- src/test/java/seedu/address/logic/commands/TakeCommandTest.java
- src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
- src/test/java/seedu/address/model/prescription/PrescriptionTest.java
- src/test/java/seedu/address/storage/JsonAdaptedPrescriptionTest.java
- src/test/java/seedu/address/testutil/EditPrescriptionDescriptorBuilder.java
- src/test/java/seedu/address/testutil/PrescriptionBuilder.java
- src/test/java/seedu/address/testutil/PrescriptionUtil.java
In v1.2, all fields were compulsory. This commit will convert
some of the intended fields to be optional
> Include optional fields into BayMeds

- src/main/java/seedu/address/MainApp.java
- src/main/java/seedu/address/logic/LogicManager.java
- src/main/java/seedu/address/model/Model.java
- src/main/java/seedu/address/model/ModelManager.java
- src/main/java/seedu/address/model/ReadOnlyPrescriptionList.java
- src/main/java/seedu/address/model/ReadOnlyUserPrefs.java
- src/main/java/seedu/address/model/UserPrefs.java
- src/main/java/seedu/address/model/util/SampleDataUtil.java
- src/main/java/seedu/address/storage/CompletedPrescriptionListStorage.java
- src/main/java/seedu/address/storage/JsonCompletedPrescriptionListStorage.java
- src/main/java/seedu/address/storage/JsonSerializableCompletedPrescriptionList.java
- src/main/java/seedu/address/storage/Storage.java
- src/main/java/seedu/address/storage/StorageManager.java
- src/main/java/seedu/address/ui/PrescriptionCard.java
- src/test/java/seedu/address/logic/LogicManagerTest.java
- src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
- src/test/java/seedu/address/logic/commands/AddCommandTest.java
- src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
- src/test/java/seedu/address/logic/commands/EditCommandTest.java
- src/test/java/seedu/address/logic/commands/FindCommandTest.java
- src/test/java/seedu/address/logic/commands/ListCommandTest.java
- src/test/java/seedu/address/logic/commands/ListTodayCommandTest.java
- src/test/java/seedu/address/logic/commands/TakeCommandTest.java
- src/test/java/seedu/address/logic/commands/UntakeCommandTest.java
- src/test/java/seedu/address/model/ModelManagerTest.java
- src/test/java/seedu/address/storage/StorageManagerTest.java
This json will store completed prescriptions, which are prescriptions 
which end date is over.
> Include a new storage json for completed prescriptions

- src/main/java/seedu/address/logic/Messages.java
- src/main/java/seedu/address/logic/commands/CommandResult.java
- src/main/java/seedu/address/logic/commands/EditCommand.java
- src/main/java/seedu/address/logic/commands/ListCompletedCommand.java
- src/main/java/seedu/address/logic/commands/TakeCommand.java
- src/main/java/seedu/address/logic/commands/UntakeCommand.java
- src/main/java/seedu/address/logic/parser/CliSyntax.java
- src/main/java/seedu/address/logic/parser/EditCommandParser.java
- src/main/java/seedu/address/logic/parser/TakeCommandParser.java
- src/main/java/seedu/address/logic/parser/UntakeCommandParser.java
- src/main/java/seedu/address/model/prescription/IsCompletedPredicate.java
- src/main/java/seedu/address/model/prescription/IsTodayPredicate.java
- src/main/java/seedu/address/model/prescription/IsValidDatesPredicate.java
- src/main/java/seedu/address/model/prescription/Stock.java
- src/main/java/seedu/address/ui/MainWindow.java
- src/test/java/seedu/address/logic/commands/CommandResultTest.java
- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
- src/test/java/seedu/address/logic/commands/EditCommandTest.java
- src/test/java/seedu/address/logic/commands/ListCompletedCommandTest.java
- src/test/java/seedu/address/logic/commands/TakeCommandTest.java
- src/test/java/seedu/address/logic/commands/UntakeCommandTest.java
- src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
- src/test/java/seedu/address/logic/parser/PrescriptionListParserTest.java
- src/test/java/seedu/address/logic/parser/TakeCommandParserTest.java
- src/test/java/seedu/address/logic/parser/UntakeCommandParserTest.java
Change implementation of certain commands and its associated test cases
> Clean up and make minor changes to commands

- docs/DeveloperGuide.md
- src/main/java/seedu/address/logic/commands/CommandResult.java
- src/main/java/seedu/address/logic/commands/ExitCommand.java
- src/main/java/seedu/address/logic/commands/HelpCommand.java
- src/main/java/seedu/address/logic/commands/ListCompletedCommand.java
- src/main/java/seedu/address/logic/commands/ListTodayCommand.java
- src/main/java/seedu/address/model/util/SampleDataUtil.java
- src/main/java/seedu/address/ui/MainWindow.java
- src/main/java/seedu/address/ui/PrescriptionCard.java
- src/main/java/seedu/address/ui/PrescriptionListPanel.java
- src/test/java/seedu/address/logic/commands/CommandResultTest.java
- src/test/java/seedu/address/logic/commands/ExitCommandTest.java
- src/test/java/seedu/address/logic/commands/HelpCommandTest.java
- src/test/java/seedu/address/logic/commands/ListTodayCommandTest.java
`list` and `listCompleted` no longer shows the "Completed" or "Incomplete" label. Only `listToday` will show the label.
Also changed the implementation of CommandResult as we are having more and more boolean variables to track `help`, `exit`, `listCompleted` and `listToday` etc. Instead of passing in a lot of boolean values to every CommandResult constructor, we use the COMMAND_WORD to track instead.
> Change CommandResult and GUI label

- build.gradle
- src/main/java/seedu/address/MainApp.java
> Update version number and build gradle for trial jar

- src/main/java/seedu/address/logic/commands/CommandResult.java
- src/main/java/seedu/address/model/prescription/Prescription.java
- src/main/java/seedu/address/ui/MainWindow.java
- src/main/java/seedu/address/ui/PrescriptionCard.java
- src/main/resources/view/DarkTheme.css
- src/main/resources/view/PrescriptionListCard.fxml
- src/test/java/seedu/address/logic/commands/CommandResultTest.java
- src/test/java/seedu/address/model/prescription/PrescriptionTest.java
Expiry Date and Total Stock header now turns Red upon the condition specified in `IsAboutToExpirePredicate` and `IsLowInStockPredicate`. This is updated whenever a Add, Take, Untake or Edit command is executed.
Does this break the abstraction barrier between frontend and backend? I can't think of any other implementations....
EDIT: CodeCov no choice uh....
> Add logic to label behaviour

- README.md
- docs/UserGuide.md
> Change aesthetics for UG according to 2101 consult

- src/main/java/seedu/address/logic/commands/EditCommand.java
Fixed issue of completed status not being updated after editing dosage.
> Fix bug in edit command

- docs/UserGuide.md
Updated misleading information, didn't change the testers point of rephrasing "Existing stock will be increase..." as it doesnt really make sense to me.
> Update untake feature in UG

- docs/DeveloperGuide.md
> Update DG with UI design considerations

- docs/UserGuide.md
- src/main/java/seedu/address/logic/parser/ParserUtil.java
- src/main/java/seedu/address/model/prescription/Dosage.java
- src/main/java/seedu/address/model/prescription/Stock.java
Note: Not fully done. But can merge in order to see the changes. Will continue to push changes with this branch subsequently.
> Standardise some aspects of UG for v1.4

- docs/UserGuide.md
- Fixed bugs that caused some HTML elements to not render properly.
- Fixed bugs that caused some inline links to not work.
- Added Table of Contents (still unsure of how it looks).
- Added a section to explain the different elements of the GUI. You can hover your cursor over the image to see the explanation. I've also added the explanation in words right below the image.
- FAQ section looks like this instead of a word dump.
> Fix UG bugs, add ToC and GUI details, change style

- src/main/java/seedu/address/logic/commands/AddCommand.java
- src/main/java/seedu/address/logic/commands/EditCommand.java
- src/main/java/seedu/address/logic/parser/PrescriptionListParser.java
- src/main/java/seedu/address/model/prescription/Dosage.java
- src/main/java/seedu/address/model/prescription/IsLowInStockPredicate.java
- src/main/java/seedu/address/model/prescription/IsTodayPredicate.java
- src/main/java/seedu/address/model/prescription/Prescription.java
remove magic numbers. improve general code quality
> improve code quality
